only_rules: # rule identifiers that should be included.
- anonymous_argument_in_multiline_closure
- block_based_kvo
- class_delegate_protocol
- comma_inheritance
- compiler_protocol_init
- contains_over_first_not_nil
- contains_over_filter_count
- contains_over_filter_is_empty
- convenience_type
- deployment_target
- discarded_notification_center_observer
- discouraged_direct_init
- discouraged_none_name
- duplicated_key_in_dictionary_literal
- empty_collection_literal
- empty_count
- empty_string
- fallthrough
- fatal_error_message
- first_where
- force_cast
- force_try
- force_unwrapping
- for_where
- function_default_parameter_at_end
# - function_parameter_count
- generic_type_name
- is_disjoint
# - large_tuple
- legacy_cggeometry_functions
- legacy_nsgeometry_functions
- legacy_constant
- legacy_constructor
- legacy_multiple
- legacy_random
- no_extension_access_modifier
- overridden_super_call
- nsobject_prefer_isequal
- prefer_self_in_static_references
- prefer_zero_over_explicit_init
- prefixed_toplevel_constant
- private_action
- private_outlet
- private_over_fileprivate
- private_unit_test
- prohibited_super_call
- protocol_property_accessors_order
- reduce_boolean
- self_in_property_initialization
- shorthand_operator
- sorted_first_last
- superfluous_disable_command
- syntactic_sugar
- todo
# - type_name
- typesafe_array_init
- unavailable_condition
- unneeded_break_in_switch
- unused_optional_binding
- unused_setter_value
- valid_ibinspectable
- weak_delegate
- xctfail_message


# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly


included: # paths to include during linting. `--path` is ignored if present.
  - "./"


excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - vendor
  - Tests
  - ProjectHelper
  - BCGAuthentication


reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
